name: Go Cross-Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
        go-version: [1.23.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-mod-${{ matrix.os }}-${{ matrix.arch }}-${{ hashFiles('go.sum') }}
        restore-keys: |
          go-mod-${{ matrix.os }}-${{ matrix.arch }}-

    - name: Install dependencies
      run: go mod download

    - name: Cross-build the project
      run: |
        GOOS=${{ matrix.os }}
        GOARCH=${{ matrix.arch }}
        go build -v -o esf-payment-backend-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} .

    - name: Copy config.yaml
      run: cp config.yaml ./esf-payment-backend-config.yaml

    - name: Package the binary and config
      run: zip -r esf-payment-backend-${{ matrix.os }}-${{ matrix.arch }}.zip esf-payment-backend-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} esf-payment-backend-config.yaml

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: go-build-package-${{ matrix.os }}-${{ matrix.arch }}
        path: ./esf-payment-backend-${{ matrix.os }}-${{ matrix.arch }}.zip
